language: python
cache: pip

python:
    - "3.5"

install:
    - pip install jupyter

script:
    - jupyter nbconvert astro_bayes.ipynb --to slides

after_success: |
    git checkout --orphan gh-pages
    git rm -rf --cached .
    mv astro_bayes.slides.html index.html
    git add -f --ignore-errors index.html img reveal.js
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
